# Generated by Django 3.0.5 on 2020-05-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('phone', models.CharField(max_length=20)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_type', models.CharField(choices=[('sms', 'Sms'), ('vms', 'Vms')], default='sms', max_length=10)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': '발신번호',
                'verbose_name_plural': '발신번호들',
                'db_table': 'sms_send_number',
            },
        ),
        migrations.CreateModel(
            name='SmsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': '발송 이력',
                'verbose_name_plural': '발송 이력들',
                'db_table': 'sms_history',
            },
        ),
    ]
