# Generated by Django 3.0.5 on 2020-05-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='url',
        ),
        migrations.AddField(
            model_name='youtube',
            name='video_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
