# Generated by Django 3.0.5 on 2020-05-19 03:57

import apps.rooms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'room_keywords',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('expense', models.IntegerField(blank=True, null=True)),
                ('contract_type', models.IntegerField(choices=[(0, 'Minimal'), (1, 'Fixed')], default=0, verbose_name='계약 종류')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='계약 시작일')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='계약 종료일')),
                ('contract_period', models.IntegerField(blank=True, null=True, verbose_name='최소 계약기간')),
                ('move_direct', models.BooleanField(default=False, verbose_name='입주 즉시 가능 여부')),
                ('move_date', models.DateField(blank=True, null=True, verbose_name='입주 날짜')),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='rooms.Keyword')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('image', models.ImageField(upload_to=apps.rooms.models.get_room_image_path)),
                ('order', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
            options={
                'db_table': 'room_images',
                'ordering': ['order', '-created'],
            },
        ),
    ]
