# Generated by Django 3.0.5 on 2020-05-19 03:57

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(choices=[(0, 'User'), (1, 'Host'), (2, 'Staff'), (3, 'Admin')], default=0)),
                ('sign_type', models.IntegerField(choices=[(0, 'Email'), (1, 'Kakao'), (2, 'Google')], default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.users.models.get_user_profile_image_path)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
                'unique_together': {('email', 'sign_type')},
            },
        ),
        migrations.CreateModel(
            name='BangdangiUser',
            fields=[
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자들',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
            ],
            options={
                'verbose_name': '호스트',
                'verbose_name_plural': '호스트들',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
